language: python

arch:
  - arm64

os: linux

services:
  - docker

before_install:
  - git clone -b 'v1.0' --depth 1 https://github.com/kubeflow/kubeflow.git
  
script:
  - cd kubeflow/components
#  - python --version
  - pip install PyYAML
  - python build_image.py --tf_version=1.6.0 tf_notebook  
  
after_script:
  - cd kubeflow
