arch:
  - arm64

os: linux

services:
  - docker

before_install:
  - git clone -b 'v1.0' --depth 1 https://github.com/kubeflow/kubeflow.git
  
script:
  - cd kubeflow/components/notebook-controller
  - docker build -t notebook-controller .
  
after_script:
  - cd kubeflow
