env:
  global:
    - REGISTRY=cestcai
    - KUBEFLOW_TAG=v1.0
  
arch:
  - arm64

os: linux

services:
  - docker

before_install:
  - docker version
  - docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
  - git clone -b ${KUBEFLOW_TAG} --depth 1 https://github.com/kubeflow/kubeflow.git
  
script:
  - cd kubeflow/components
  - docker build -t ${REGISTRY}/notebook-controller:${KUBEFLOW_TAG} -f notebook-controller/Dockerfile .
  - docker push ${REGISTRY}/notebook-controller:${KUBEFLOW_TAG} 
  
  - docker build -t ${REGISTRY}/tensorboard-controller:${KUBEFLOW_TAG} -f  tensorboard-controller/Dockerfile .
  - docker push ${REGISTRY}/tensorboard-controller:${KUBEFLOW_TAG}  
  
  #- cd centraldashboard
  #- docker build -t centraldashboard . 
  #- cd ..
  
  - cd jupyter-web-app
  - docker build -t ${REGISTRY}/jupyter-web-app:${KUBEFLOW_TAG}  .
  - docker push ${REGISTRY}/jupyter-web-app:${KUBEFLOW_TAG}
  - cd ..
  
  - cd profile-controller
  - docker build  -t ${REGISTRY}/profile-controller:${KUBEFLOW_TAG} .
  - docker push ${REGISTRY}/profile-controller:${KUBEFLOW_TAG}
  - cd ..
#  - cd access-management 
#  - docker build -t access-management .
#  - cd ..
  - cd admission-webhook
  - docker build -t ${REGISTRY}/admission-webhook:${KUBEFLOW_TAG} .
  - docker push ${REGISTRY}/admission-webhook:${KUBEFLOW_TAG} 
  - cd ..
  
  - cd gatekeeper
  - docker build -t gatekeeper .
  - cd ..
  - cd kflogin
  - docker build -t kflogin .
  - cd .. 
  - cd static-config-server
  - docker build -t static-config-server .
  - cd .. 

after_script:
  - cd kubeflow
