env:
  - REGISTRY=cestcai
  - KUBEFLOW_TAG=v1.0
  
arch:
  - arm64

os: linux

services:
  - docker

before_install:
  - docker version
  - docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
  - git clone -b ${KUBEFLOW_TAG} --depth 1 https://github.com/kubeflow/kubeflow.git
  
script:
  - cd kubeflow/components
#  - python --version
#  - pip install PyYAML
#  - python build_image.py --tf_version=1.6.0 tf_serving
  - docker build -t notebook-controller -f notebook-controller/Dockerfile .
  - docker build -t tensorboard-controller -f  tensorboard-controller/Dockerfile .
  - cd centraldashboard
  - docker build -t centraldashboard . 
  - cd ..
  - cd jupyter-web-app
  - docker build -t jupyter-web-app . 
  - cd ..
  - cd profile-controller
  - docker build -t profile-controller . 
  - cd ..
#  - cd access-management 
#  - docker build -t access-management .
#  - cd ..
  - cd admission-webhook
  - docker build -t ${REGISTRY}/admission-webhook:${KUBEFLOW_TAG} .
  - docker push ${REGISTRY}/admission-webhook:${KUBEFLOW_TAG} 
  - cd ..
  
  - cd gatekeeper
  - docker build -t gatekeeper .
  - cd ..
  - cd kflogin
  - docker build -t kflogin .
  - cd .. 
  - cd static-config-server
  - docker build -t static-config-server .
  - cd .. 

after_script:
  - cd kubeflow
